### ISSUE TITLE
今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文件和源码Line.ts第65、70行相对应的地方改掉就可以了

### ISSUE THREAD

**Issue by lvjunxiang** [synyi/poplar#26]
今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文件和源码Line.ts第65、70行相对应的地方改掉就可以了

_Originally posted by @dllmm in https://github.com/synyi/poplar/issues/16#issuecomment-486130700_

**Comment by lvjunxiang** [comment]
大佬，想向你请教一下怎么使用这个工具，不知道方不方便呢？(qq:1216498454)

**Comment by dllmm** [comment]
https://synyi.github.io/poplar/
这个demo已经把所有的JS封装好了 直接拿来用就可以了




------------------ 原始邮件 ------------------
发件人: "lvjunxiang"<notifications@github.com>;
发送时间: 2019年6月24日(星期一) 中午11:19
收件人: "synyi/poplar"<poplar@noreply.github.com>;
抄送: "Meぺ纯属主角"<554624024@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [synyi/poplar] 今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文件和源码Line.ts第65、70行相对应的地方改掉就可以了 (#26)




大佬，想向你请教一下怎么使用这个工具，不知道方不方便呢？(qq:1216498454)

**Comment by lvjunxiang** [comment]
我就是按他的那个文档，在js里面引入，一引入就报错了------------------ 原始邮件 ------------------
发件人: "dllmm"<notifications@github.com>
发送时间: 2019年6月24日(星期一) 中午11:36
收件人: "synyi/poplar"<poplar@noreply.github.com>;
抄送: "lvjunxiang"<1216498454@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [synyi/poplar] 今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文件和源码Line.ts第65、70行相对应的地方改掉就可以了 (#26)


https://synyi.github.io/poplar/ 
 这个demo已经把所有的JS封装好了 直接拿来用就可以了 
 
 
 
 
 ------------------ 原始邮&#x4EF6; ------------------ 
 发&#x4EF6;人: "lvjunxiang"<notifications@github.com>; 
 发送时间: 2019年6月24日(星期一) 中午11:19 
 收&#x4EF6;人: "synyi/poplar"<poplar@noreply.github.com>; 
 抄送: "Meぺ纯属主角"<554624024@qq.com>;"Mention"<mention@noreply.github.com>; 
 主题: Re: [synyi/poplar] 今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文&#x4EF6;和源码Line.ts第65、70行相对应的地方改掉就可以了 (#26) 
 
 
 
 
 大佬，想向你请教一下怎么使用这个工具，不知道方不方便呢？(qq:1216498454) 
   
 — 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;

**Comment by dllmm** [comment]
这几个文件你有么


------------------ 原始邮件 ------------------
发件人: "lvjunxiang"<notifications@github.com>;
发送时间: 2019年6月24日(星期一) 下午2:22
收件人: "synyi/poplar"<poplar@noreply.github.com>;
抄送: "Meぺ纯属主角"<554624024@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [synyi/poplar] 今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文件和源码Line.ts第65、70行相对应的地方改掉就可以了 (#26)



我就是按他的那个文档，在js里面引入，一引入就报错了------------------ 原始邮件 ------------------ 
 发件人: "dllmm"<notifications@github.com> 
 发送时间: 2019年6月24日(星期一) 中午11:36 
 收件人: "synyi/poplar"<poplar@noreply.github.com>; 
 抄送: "lvjunxiang"<1216498454@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [synyi/poplar] 今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文件和源码Line.ts第65、70行相对应的地方改掉就可以了 (#26) 
 
 
 https://synyi.github.io/poplar/  
  这个demo已经把所有的JS封装好了 直接拿来用就可以了  
   
   
   
   
  ------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "lvjunxiang"<notifications@github.com>;  
  发送时间: 2019年6月24日(星期一) 中午11:19  
  收&#x4EF6;人: "synyi/poplar"<poplar@noreply.github.com>;  
  抄送: "Meぺ纯属主角"<554624024@qq.com>;"Mention"<mention@noreply.github.com>;  
  主题: Re: [synyi/poplar] 今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文&#x4EF6;和源码Line.ts第65、70行相对应的地方改掉就可以了 (#26)  
   
   
   
   
  大佬，想向你请教一下怎么使用这个工具，不知道方不方便呢？(qq:1216498454)  
     
  —  
  You are receiving this because you were mentioned.  
  Reply to this email directly, view it on GitHub, or mute the thread.  
 &mdash;

**Comment by lvjunxiang** [comment]
有的，我用npm下的那个工具，然后在文件夹中创建一个js和html,js中导入，html在把js引过来，打开页面控制台就保错;还尝试了搭建了一个vue项目，在项目中安装这个，我也查看了这个工具的源文件，没有什么缺失，然后就是在helloWorld.vue的script中导入，也同样是保错的。我想问一下，是不是我的操作问题呀------------------ 原始邮件 ------------------
发件人: "dllmm"<notifications@github.com>
发送时间: 2019年6月24日(星期一) 下午2:46
收件人: "synyi/poplar"<poplar@noreply.github.com>;
抄送: "lvjunxiang"<1216498454@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [synyi/poplar] 今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文件和源码Line.ts第65、70行相对应的地方改掉就可以了 (#26)


这几个文&#x4EF6;你有么 
 
 
 ------------------ 原始邮&#x4EF6; ------------------ 
 发&#x4EF6;人: "lvjunxiang"<notifications@github.com>; 
 发送时间: 2019年6月24日(星期一) 下午2:22 
 收&#x4EF6;人: "synyi/poplar"<poplar@noreply.github.com>; 
 抄送: "Meぺ纯属主角"<554624024@qq.com>;"Mention"<mention@noreply.github.com>; 
 主题: Re: [synyi/poplar] 今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文&#x4EF6;和源码Line.ts第65、70行相对应的地方改掉就可以了 (#26) 
 
 
 
 我就是按他的那个文档，在js里面引入，一引入就报错了------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "dllmm"<notifications@github.com>  
  发送时间: 2019年6月24日(星期一) 中午11:36  
  收&#x4EF6;人: "synyi/poplar"<poplar@noreply.github.com>;  
  抄送: "lvjunxiang"<1216498454@qq.com>;"Author"<author@noreply.github.com>;  
  主题: Re: [synyi/poplar] 今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文&#x4EF6;和源码Line.ts第65、70行相对应的地方改掉就可以了 (#26)  
   
   
  https://synyi.github.io/poplar/   
   这个demo已经把所有的JS封装好了 直接拿来用就可以了   
     
     
     
     
   ------------------ 原始邮&#x4EF6; ------------------   
   发&#x4EF6;人: "lvjunxiang"<notifications@github.com>;   
   发送时间: 2019年6月24日(星期一) 中午11:19   
   收&#x4EF6;人: "synyi/poplar"<poplar@noreply.github.com>;   
   抄送: "Meぺ纯属主角"<554624024@qq.com>;"Mention"<mention@noreply.github.com>;   
   主题: Re: [synyi/poplar] 今天看了下源码 poplar\src\Annotator\Store\Entities路径下的Line.ts中的第65行！!。.？?"\n这里把.去掉还有第70行！!。.？?”"a-zA-Z这里也把.去掉 小数点就不会换行了 demo中找到vendor.6884fc746c954a8feea5.js这个文&#x4EF6;和源码Line.ts第65、70行相对应的地方改掉就可以了 (#26)   
     
     
     
     
   大佬，想向你请教一下怎么使用这个工具，不知道方不方便呢？(qq:1216498454)   
       
   —   
   You are receiving this because you were mentioned.   
   Reply to this email directly, view it on GitHub, or mute the thread.   
  &mdash;  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or mute the thread.  
 — 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;

**Comment by longfangsong** [comment]
fixed in v2
